version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eduai
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ./apps/api
    env_file:
      - ../.env
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./apps/api:/usr/src/app
  web:
    build: ./apps/web
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    depends_on:
      - api
    volumes:
      - ./apps/web:/usr/src/app
volumes:
  db_data:
