openapi: 3.0.0
info:
  title: Edu AI API
  version: 1.0.0
  description: API documentation for Edu AI App
servers:
  - url: http://localhost:4000
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: User registered
  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT token
  /user/me:
    get:
      summary: Get current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User info
  /schools:
    get:
      summary: List schools
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of schools
    post:
      summary: Create a school
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                domain:
                  type: string
      responses:
        '200':
          description: School created
  /assignments:
    get:
      summary: List assignments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of assignments
    post:
      summary: Create an assignment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                dueDate:
                  type: string
                  format: date-time
                schoolId:
                  type: integer
      responses:
        '200':
          description: Assignment created
  /ai/chat:
    post:
      summary: Chat with OpenAI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
      responses:
        '200':
          description: AI response
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
